workspace:
  base: /go
  path: src/github.com/Oxyyx/zeal

pipeline:
  build:
    image: golang
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_CONFIG=postgres://zeal_test:zeal_test@postgres:5432/zeal_test?sslmode=disable
    commands:
      - sleep 15
      - go get github.com/gorilla/mux
      - go get github.com/urfave/cli
      - go get github.com/jinzhu/gorm
      - go get github.com/lib/pq
      - go test -v ./...

services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=zeal_test
    - POSTGRES_DB=zeal_test
    - POSTGRES_PASSWORD=zeal_test